CREATE OR REPLACE FUNCTION public.get_all_notes(
	)
    RETURNS SETOF notes
    LANGUAGE 'plpgsql'
    COST 100
    VOLATILE PARALLEL UNSAFE
    ROWS 1000

AS $BODY$
BEGIN
RETURN QUERY SELECT * FROM notes;
END;
$BODY$;